name = "Laika"
id = 6942

priority_fee_oracle_type = "USAGE_BASED"
min_max_priority_fee_per_gas = "0x06FC23AC00" # 30_000_000_000
bloxroute_enabled = false
flashbots_enabled = false
max_transaction_size_bytes = 130000
